on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-test:
    name: build apps using cmake/Xcode for macOS 10.15 and ctest library
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate build system
        run: cmake -S . -B build -GXcode -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DAV_SPEECH_IN_NOISE_ENABLE_TESTS=1 -DCMAKE_Swift_LANGUAGE_VERSION=5
      - name: build tests
        run: cmake --build build --target av-speech-in-noise-test-exe --config Release
      - name: test library
        run: ctest -V -C Release
        working-directory: ./build
      - name: build app
        run: cmake --build build --target av-speech-in-noise-macos-bundle --config Release
      - name: build facemask study
        run: cmake --build build --target av-speech-in-noise-facemask-study-macos-bundle --config Release
