name: build and test

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-test:
    name: build using cmake/Xcode for macOS 10.13 and ctest library
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate build system
        run: cmake -S . -B build -GXcode -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DAV_SPEECH_IN_NOISE_ENABLE_TESTS=1
      - name: build tests
        run: cmake --build build --target tests --config Release
      - name: test library
        run: |
          cd ./build
          ctest -V -C Release
      - name: build app
        run: cmake --build build --target AvSpeechInNoise --config Release
